-- Brandex Central Processing: normalized, dummy-data-safe foundation.
-- Apply only to a development Supabase project. No production data is referenced.
create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null, role text not null default 'operator' check (role in ('admin','operator','viewer')), created_at timestamptz not null default now());
create table if not exists public.clients (id uuid primary key default gen_random_uuid(), client_code text not null unique, name text not null, phone text, email text, city text, cnic text, created_at timestamptz not null default now());
create table if not exists public.cases (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete restrict, case_number integer not null check (case_number > 0), business_case_id text not null unique, tm_number text unique, applicant_name text not null, cnic text, mark text not null, class_code text not null, application_type text not null default 'Trademark', city text, stage text not null default 'Stage 1' check (stage in ('Stage 1','Stage 2','Stage 3','Stage 4')), sub_stage text not null, status text not null default 'Active' check (status in ('Active','Completed','On hold')), filing_date date, acknowledgement_date date, acknowledgement_due_at timestamptz not null, opened_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (client_id, case_number));
create unique index if not exists cases_business_case_id_idx on public.cases (business_case_id);
create index if not exists cases_search_idx on public.cases (client_id, stage, sub_stage, tm_number, class_code);
create table if not exists public.case_services (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, service_name text not null, created_at timestamptz not null default now());
create table if not exists public.workflow_history (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, from_stage text, to_stage text not null, sub_stage text not null, reason text, actor_id uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.events (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, event_type text not null, description text not null, metadata jsonb not null default '{}'::jsonb, actor_id uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.documents (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, document_type text not null, title text not null, storage_path text, status text not null default 'Pending' check (status in ('Verified','Pending','Missing')), notes text, uploaded_by uuid references auth.users(id), uploaded_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, payment_type text not null check (payment_type in ('Client payment','Agent fee')), stage text not null, amount numeric(12,2) not null check (amount >= 0), payment_date date not null, status text not null default 'Pending' check (status in ('Received','Pending')), reference text, notes text, created_at timestamptz not null default now());
create table if not exists public.agents (id uuid primary key default gen_random_uuid(), name text not null, city text, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.case_agents (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, agent_id uuid not null references public.agents(id) on delete restrict, assigned_at timestamptz not null default now(), removed_at timestamptz, notes text, unique(case_id, agent_id, assigned_at));
create table if not exists public.ledger_entries (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, entry_date date not null, detail text not null, stage text not null, due numeric(12,2) not null default 0, received numeric(12,2) not null default 0, check (due >= 0 and received >= 0));
create table if not exists public.checks (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, check_type text not null, severity text not null check (severity in ('info','warning','critical')), status text not null default 'Open' check (status in ('Open','Resolved')), message text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), resolved_at timestamptz);
create table if not exists public.notes (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade, body text not null, author_id uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), table_name text not null, record_id uuid not null, action text not null, actor_id uuid references auth.users(id), old_values jsonb, new_values jsonb, created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.clients enable row level security; alter table public.cases enable row level security; alter table public.events enable row level security; alter table public.documents enable row level security; alter table public.payments enable row level security; alter table public.agents enable row level security; alter table public.case_agents enable row level security; alter table public.ledger_entries enable row level security; alter table public.checks enable row level security; alter table public.notes enable row level security; alter table public.audit_logs enable row level security;
do $$ declare t text; begin foreach t in array array['profiles','clients','cases','events','documents','payments','agents','case_agents','ledger_entries','checks','notes','audit_logs'] loop execute format('drop policy if exists "authenticated_read_%1$s" on public.%1$s', t); execute format('create policy "authenticated_read_%1$s" on public.%1$s for select to authenticated using (true)', t); end loop; end $$;
insert into storage.buckets (id, name, public) values ('case-documents', 'case-documents', false) on conflict (id) do nothing;

-- Intentionally no trigger connects payments to agent fees. Those are explicit records.
